apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: node-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: app
          image: falcon007/node-docker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000