version: '3.3'
services:
  mysql-app:
    image: falcon007/third-mysql-app:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=db
      - DATABASE_PORT=3306
    networks:
      - my-network
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - my-network
# Names our volume
networks:
  my-network:
    driver: bridge

volumes:
  my-db: