apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: python-namespace
  labels:
    app: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
        - name: pythonapp
          image: falcon007/python-docker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000