apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  serviceName: "node-service"
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: app
          image: falcon007/node-docker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000